version: "3.9"
services:
  cvmfs:
    image: "gitlab-registry.cern.ch/vcs/cvmfs-automounter:master"
    pid: "host"
    user: "0"
    privileged: true
    restart: always
    volumes:
      - type: bind
        source: /shared-mounts
        target: /cvmfsmounts
        bind:
          propagation: rshared
  gui:
    #image: "gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cc7-cvmfs"
    build: ./dqmgui
    image: "gitlab-registry.cern.ch/rrabadan/gemdqm-dev/dqmgui:testbeam"
    stdin_open: true
    tty: true
    network_mode: host
    
  processor:
    image: "gitlab-registry.cern.ch/rrabadan/gemsw:d0a6bb5a"
    depends_on:
      - cvmfs
      - gui
    environment:
      - WDIR=/home/cmsusr
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: /shared-mounts/cvmfs
        target: /cvmfs
        bind:
          propagation: rslave
      - type: bind
        source: ./processor
        target: /home/cmsusr/processor
      - type: bind
        source: ./data
        target: /data
        bind:
          propagation: rslave
    working_dir: /home/cmsusr 
    command: "bash processor/run-testbeam.sh"
    network_mode: host
